openapi: 3.1.0
info:
  title: Play Schema Driven Development
  version: 1.0.0
  description: Play Framework スキーマ駆動開発サンプル
servers:
  - url: http://localhost:9000
    description: ローカル開発環境
tags:
  - name: user
    description: ユーザーAPI
paths:
  /api/v1/users:
    get:
      tags:
        - user
      summary: ユーザー一覧取得
      description: ユーザー一覧の取得
      responses:
        '200':
          description: ユーザー一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - user
      summary: ユーザー登録
      description: ユーザーの登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: ユーザー登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
        - user
      summary: ユーザー削除
      description: ユーザーの削除
      responses:
        '204':
          description: ユーザー削除成功
components:
  schemas:
    UserName:
      type: object
      properties:
        firstName:
          type: string
          description: ユーザー名(姓)
        lastName:
          type: string
          description: ユーザー名(名)
      required:
        - firstName
        - lastName
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ユーザーID
        name:
          $ref: '#/components/schemas/UserName'
        email:
          type: string
          description: メールアドレス
        age:
          type: integer
          format: int32
          description: 年齢
      required:
        - id
        - name
        - email
